# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20161201_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='camera',
            field=models.CharField(default='Olympus', max_length=32),
        ),
        migrations.AlterField(
            model_name='picture',
            name='date',
            field=models.DateField(verbose_name='date taken'),
        ),
    ]
