# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20161202_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.CharField(default='Description here.', max_length=512),
        ),
    ]
