# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20161203_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(),
        ),
    ]
